---
program: /home/groups/swl1/mkounga/code/Zoltowski_S5/run_train.py
method: random
metric:
  goal: maximize
  name: val_acc
parameters:
  n_layers:
    values: [6, 8, 10, 12]
  bsz:
    value: 64
  wandb_project:
    value: 'Speech_BCI_Tune'
  wandb_entity:
    value: 'maxkounga'
  epochs:
    value: 200
  USE_WANDB:
    value: True
  dataset:
    value: 'BCI-classification'
  dir_name:
    value: '/scratch/users/mkounga/competitionDataProcessed/'
  early_stop_patience:
    value: 50
  d_model:
    values: [256, 512, 1024]
  ssm_size_base:
    values: [64, 128, 256, 512]
  p_dropout:
    values: [0.0, 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5]
  ssm_lr_base:
    values: [1e-2, 3e-3, 1e-3, 3e-4, 1e-4]
  jax_seed:
    min: 1111
    max: 5311
  lr_factor:
    values: [3, 2, 1, 0.5]
  gauss_std:
    values: [0.01, 0.1, 0.2, 0.4, 0.8, 1.0]
  bias_std:
    values: [0.01, 0.05, 0.1, 0.2, 0.4]
  smoothing:
    values: [True, False]
  smooth_sigma:
    values: [1.0, 2.0]
  smooth_width:
    values: [10, 20]
  blocks:
    values: [8, 16, 32, 64]
  downsampling:
    values: ['standard', 'beginning', 'end', 'middle', 'none']
  bidirectional:
    value: True


