---
program: /home/groups/swl1/mkounga/code/neural_seq_decoder/run_train_mamba.py
method: random
metric:
  goal: minimize
  name: cer
parameters:
  USE_WANDB:
    value: True
  wandb_project:
    value: 'Mamba_Tune'
  wandb_entity:
    value: 'maxkounga'
  batchSize:
    values: [16, 32, 64, 128]
  lrStart:
    values: [1e-2, 3e-3, 1e-3, 3e-4, 1e-4]
  nLayers:
    values: [2, 4, 6, 8, 10]
  seed:
    min: 1111
    max: 5311
  dropout:
    values: [0.0, 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5]
  whiteNoiseSD:
    values: [0.0, 0.2, 0.4, 0.8]
  constantOffsetSD:
    values: [0.01, 0.1, 0.2, 0.4, 0.8, 1.0]
  gaussianSmoothWidth:
    values: [0.0, 0.5, 1.0]
  strideLen:
    values: [4 32, 1 1, 2 4, 2 2, 4 8]
  bidirectional:
    value: True
  d_model:
    values: [64, 128, 256, 512, 1024]
  d_state:
    values: [8, 16, 32]
  d_conv:
    values: [2, 4]


